# Generated by Django 4.1.5 on 2023-01-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_project_options_alter_project_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Dirección Web"),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Título"),
        ),
    ]
